linters:
  disable-all: true
  enable:
    - errcheck
    - errorlint
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign

linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
